### PR TITLE
Don’t format small sizes as kB.

### PR DESCRIPTION
**Pull request by tobli**
Currently byte sizes are always shown with a kb approximation. This is not helpful for  small sizes, e.g. 5 bytes (~0 kb). Instead leave out the kb approximation for sizes < 1kB. Also:
- change from kb (kilobit) to kB (kilobyte)
- show as MB for sizes >= 1MB
- don’t use decimals for approximate sizes < 1MB. The difference between e.g. 67 kB and 68 kB is small, and integer sizes are more glanceable.

### CODE REVIEW

**Comment by tobli** [comment]
Remember to squash when merging! I messed up and had 1MB as 1014kB initially.

**Comment by tobli** [comment]
@micmro I used the same constant style as for the seconds formatting for now, but we can change later if needed.

**Comment by tobli** [comment]
bytes

This is how sizes over and under 1kB are displayed with this PR.

**Comment by micmro** [comment]
Great - love all the small UX improvements, makes it it so much easier to read.

**Pull request merged**
