### PR TITLE
Move request number to the far left.

### PR DESCRIPTION
**Pull request by tobli**

### CODE REVIEW

**Comment by tobli** [comment]
number-to-the-left

@micmro, @soulgalore - not sure if it's better, but putting up a PR for discussion.

**Comment by soulgalore** [comment]
I think like it is today is better, it seems cleaner?

**Comment by micmro** [comment]
I don't have a strong opinion on that one. Though If we go for this we should give it a bit more spacing, or possibly switch the icons around to make the request name more visible. Quickly mocked it up a bit to see:

Current (right):
current

Left (space adjusted):
v1

Left (icons swapped):
v2

**Comment by tobli** [comment]
The margins are constants, so it's easy to tweak them and the layout will adjust accordingly. We can close this one, and revive it later if needed.

**Pull request closed without merging**
