### PR TITLE
Fix for getting exp feature and added H2 priority

### PR DESCRIPTION
**Pull request by soulgalore**
Fixed a small bug for getting extra info from the HAR file + added field for H2 prio (at least how WPT uses it).

### CODE REVIEW

**Comment by andydavies** [comment]
Not that it affects the PR but just for info the priority is Chrome's internal one rather than a H2 one.

**Comment by soulgalore** [comment]
yes you are right, WPT calls it priority, so I added that now. In sitespeed we will keep it in the request and call internalPriority, so I will do a fix when it's out.

**Comment by soulgalore** [comment]
let me rename it later for clarity.

**Comment by soulgalore** [comment]
haha oopps sorry this is bad day. I'll just kill this PR and send a new one :)

**Pull request closed without merging**
