### PR TITLE
Set row max time from outside of PerfCascade

### PR DESCRIPTION
**Pull request by soulgalore**
The use case for this is when you wanna put to waterfall charts on top on each other and you wanna make sure they have the same time line, so it is easier to compare them.

### CODE REVIEW

**Comment by soulgalore** [comment]
hmm Travis fails, it's a new updated tslint that gets installed.

**Comment by micmro** [comment]
Hi Peter. Thanks for the PR. I'm just traveling Norther Irland and are on
the road a lot, will look at this when I head to Canada in a few days.

Best,
Michael


On 22 Aug 2017 7:05 a.m., "Peter Hedenskog" <notifications@github.com>
wrote:

hmm Travis fails, it's a new updated tslint that gets installed.

—
You are receiving this because your review was requested.

Reply to this email directly, view it on GitHub
<https://github.com/micmro/PerfCascade/pull/211#issuecomment-323927968>,
or mute
the thread

**Comment by soulgalore** [comment]
No worries. I'll update the dependencies. Need your help then how you want the interface for options, I don't fully follow that :)

**Comment by micmro** [comment]
Looks good, but should we perhaps call it `fixedDurationMs` or `fixedLengthMs`  instead of `rowMaxTimeInMs`?

**Review by micmro — APPROVED** [review]

**Comment by soulgalore** [comment]
Yes agree, changed the name!

**Pull request merged**
