### PR TITLE
Rename showMimeType option to showMimeTypeIcon

### PR DESCRIPTION
**Pull request by tobli**

### CODE REVIEW

**Review by micmro — CHANGES_REQUESTED** [review]
Thanks, totally forgot that one.
Sorry didn't think about this before but while seeing it in context would it be more in line with the other if we call it `showMimeTypeIcon` instead? Or change the other one as well?

**Comment by tobli** [comment]
True, that's better. I'll update both code and documentation to showMimeTypeIcon and force push to this PR.

I've got a few other changes in the works that I'd like to propose/discuss. Some of which would benefit from some preparatory refactorings to avoid massive changes. How to best go about with that? I see you often make a release after each merged PR. For changes that are internal (not affecting public api and/or features) that might not be needed. I could open PR's and keep pushing commits to them as a forum for discussion.

**Review by micmro — APPROVED** [review]

**Comment by micmro** [comment]
Thanks a lot for the change, all perfect now (I've added you to the contributors list as well, so you can merge it whenever you want).

Yes, I like that idea and I think it would work well. Usually I'd neither make a release unless it changes the API or behavior (e.g. a bugfix, feature), but I might have absentmindedly done it a few times anyway :)

**Comment by tobli** [comment]
Thanks @micmro!
I have one concern. Right now I didn't include changes to the generated src/dist folder in the patch. Doing a release with grunt does take care of that, so that'd be an argument for doing a release after each merge. The Readme refers to [scr/dist](https://github.com/micmro/PerfCascade/tree/master/src/dist) as a source to get the latest javascript/css, but including it in every commit would be a bit of a barrier (would add noise to patch reviewing etc.).
One approach could be to remove generated files from git, and instead use grunt to zip up the dist folder when doing a release, and publishing that on GitHub releases. That'd make npm install, or GitHub releases download the canonical sources for release artefacts, and have git only be source code (.ts and raw css). Would that make sense?

**Comment by micmro** [comment]
Good idea! I wanted to overthink the release folder structure anyway, it's a bit organically grown and there are a few things we need to consider:
- adding the combined type definition files for the NPM module (or all) 
- automatic release of the [staging page](https://micmro.github.io/PerfCascade/)

**Pull request merged**
